# Data Cleaning Projek Urban Heat Island

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

## Data AWS

### Informasi Dataset AWS

```
'Date': Tanggal pengukuran.
'Time': Waktu pengukuran.
'Temp Out': Temperatur udara di luar.
'Hi Temp': Temperatur tertinggi yang tercatat.
'Low Temp': Temperatur terendah yang tercatat.
'Out Hum': Kelembaban udara di luar.
'Dew Pt.': Titik embun.
'Wind Speed': Kecepatan angin.
'Wind Dir': Arah angin.
'Wind Run': Jarak yang ditempuh oleh angin dalam satu periode waktu tertentu.
'Hi Speed': Kecepatan angin tertinggi yang tercatat.
'Hi Dir': Arah angin saat kecepatan tertinggi terjadi.
'Wind Chill': Sensasi dingin yang dirasakan oleh tubuh karena angin dan suhu udara.
'Heat Index': Indeks suhu yang menggambarkan sensasi panas yang dirasakan oleh tubuh.
'THW Index': Indeks panas yang memperhitungkan suhu udara, kelembaban, dan angin.
'Bar': Tekanan udara atmosfer.
'Rain': Jumlah curah hujan yang tercatat.
'Rain Rate': Intensitas curah hujan dalam satuan waktu tertentu.
'Heat D-D': Derajat hari (Degree Days) untuk pendinginan.
'Cool D-D': Derajat hari (Degree Days) untuk pemanasan.
'In Temp': Temperatur di dalam ruangan.
'In Hum': Kelembaban di dalam ruangan.
'In Dew': Titik embun di dalam ruangan.
'In Heat': Panas di dalam ruangan.
'In EMC': Kandungan air dalam material.
'In Air Density': Kepadatan udara di dalam ruangan.
'Wind Samp': Sampel kecepatan angin.
'Wind Tx': Transmisi data kecepatan angin.
'ISS Recept': Penerima data stasiun cuaca.
'Arc. Int.': Intensitas radiasi sinar matahari yang diterima.
```

### AWS - Data Cleaning

#### Data Sebelum Pengecetan

In [3]:
aws_bef = pd.read_excel('/content/drive/MyDrive/Satu Data/Data KKN/AWS 29 Desember - 1 Januari 2024.xlsx')
aws_bef.head()

,Date,Time,Temp Out,Hi Temp,Low Temp,Out Hum,Dew Pt.,Wind Speed,Wind Dir,Wind Run,Hi Speed,Hi Dir,Wind Chill,Heat Index,THW Index,Bar,Rain,Rain Rate,Heat D-D,Cool D-D,In Temp,In Hum,In Dew,In Heat,In EMC,In Air Density,Wind Samp,Wind Tx,ISS Recept,Arc. Int.
0,2023-12-29,10:00:00,32.0,32.1,31.9,69,25.6,0.4,W,0.24,0.9,WSW,32.0,40.1,40.1,1014.6,0.0,0.0,0.000,0.095,32.9,66,25.7,41.6,11.65,11180,121,1,53.1,10
1,2023-12-29,10:10:00,31.8,31.9,31.8,71,25.9,0.4,NNW,0.27,1.3,NNW,31.8,40.3,40.3,1014.6,0.0,0.0,0.000,0.094,32.1,69,25.7,40.3,12.35,11212,234,1,100.0,10
2,2023-12-29,10:20:00,31.7,31.8,31.6,71,25.8,0.4,ENE,0.27,1.8,WNW,31.7,39.8,39.8,1014.2,0.0,0.0,0.000,0.093,31.2,71,25.3,38.6,12.85,11245,84,1,36.8,10
3,2023-12-29,10:30:00,32.1,32.4,31.7,69,25.7,0.9,N,0.54,2.2,W,32.1,40.4,40.4,1014.0,0.0,0.0,0.000,0.096,31.2,71,25.3,38.4,12.85,11246,227,1,99.6,10
4,2023-12-29,10:40:00,32.5,32.6,32.4,69,26.1,0.9,NNE,0.54,3.6,N,32.5,41.6,41.6,1014.1,0.0,0.0,0.000,0.098,31.2,71,25.3,38.6,12.85,11244,166,1,72.8,10

In [4]:
aws_bef = aws_bef.iloc[3:430].reset_index(drop=True)

In [5]:
aws_bef.head()

,Date,Time,Temp Out,Hi Temp,Low Temp,Out Hum,Dew Pt.,Wind Speed,Wind Dir,Wind Run,Hi Speed,Hi Dir,Wind Chill,Heat Index,THW Index,Bar,Rain,Rain Rate,Heat D-D,Cool D-D,In Temp,In Hum,In Dew,In Heat,In EMC,In Air Density,Wind Samp,Wind Tx,ISS Recept,Arc. Int.
0,2023-12-29,10:30:00,32.1,32.4,31.7,69,25.7,0.9,N,0.54,2.2,W,32.1,40.4,40.4,1014.0,0.0,0.0,0.000,0.096,31.2,71,25.3,38.4,12.85,11246,227,1,99.6,10
1,2023-12-29,10:40:00,32.5,32.6,32.4,69,26.1,0.9,NNE,0.54,3.6,N,32.5,41.6,41.6,1014.1,0.0,0.0,0.000,0.098,31.2,71,25.3,38.6,12.85,11244,166,1,72.8,10
2,2023-12-29,10:50:00,32.1,32.4,31.9,72,26.4,0.9,NE,0.54,2.2,NE,32.1,41.6,41.6,1014.1,0.0,0.0,0.000,0.096,31.2,71,25.3,38.4,12.85,11246,231,1,100.0,10
3,2023-12-29,11:00:00,32.0,32.0,31.9,70,25.8,0.4,WNW,0.27,1.8,WNW,32.0,40.4,40.4,1013.8,0.0,0.0,0.000,0.095,31.9,70,25.7,40.2,12.55,11207,87,1,38.2,10
4,2023-12-29,11:10:00,31.8,31.9,31.8,69,25.4,0.4,NNW,0.27,2.2,NE,31.8,39.7,39.7,1013.8,0.0,0.0,0.000,0.094,32.0,70,25.8,40.4,12.55,11200,234,1,100.0,10

In [6]:
# Mengecek kolom yang terdapat nilai '---'
def check_for_dashes(column):
    return '---' in column.values

columns_with_dashes = aws_bef.apply(check_for_dashes)
columns_with_dashes[columns_with_dashes].index.tolist()

<ipython-input-6-45de183517a9>:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return '---' in column.values

['Temp Out',
 'Hi Temp',
 'Low Temp',
 'Out Hum',
 'Dew Pt.',
 'Wind Dir',
 'Hi Dir',
 'Wind Chill',
 'Heat Index',
 'THW Index',
 'Heat D-D',
 'Cool D-D']

In [7]:
aws_bef.replace('---', np.nan, inplace=True)

In [8]:
aws_bef.isnull().sum()

Date               0
Time               0
Temp Out           5
Hi Temp            5
Low Temp           5
Out Hum            3
Dew Pt.            5
Wind Speed         0
Wind Dir          70
Wind Run           0
Hi Speed           0
Hi Dir            70
Wind Chill         5
Heat Index         5
THW Index          5
Bar                0
Rain               0
Rain Rate          0
Heat D-D           5
Cool D-D           5
In Temp            0
In Hum             0
In Dew             0
In Heat            0
In EMC             0
In Air Density     0
Wind Samp          0
Wind Tx            0
ISS Recept         0
Arc. Int.          0
dtype: int64

In [9]:
aws_bef.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 30 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            427 non-null    datetime64[ns]
 1   Time            427 non-null    object
 2   Temp Out        422 non-null    object
 3   Hi Temp         422 non-null    object
 4   Low Temp        422 non-null    object
 5   Out Hum         424 non-null    float64
 6   Dew Pt.         422 non-null    object
 7   Wind Speed      427 non-null    float64
 8   Wind Dir        357 non-null    object
 9   Wind Run        427 non-null    float64
 10  Hi Speed        427 non-null    float64
 11  Hi Dir          357 non-null    object
 12  Wind Chill      422 non-null    object
 13  Heat Index      422 non-null    object
 14  THW Index       422 non-null    object
 15  Bar             427 non-null    float64
 16  Rain            427 non-null    float64
 17  Rain Rate       427 non-null    float64
 18  Heat D-D        422 non-null    object
 19  Cool D-D        422 non-null    object
 20  In Temp         427 non-null    float64
 21  In Hum          427 non-null    int64
 22  In Dew          427 non-null    float64
 23  In Heat         427 non-null    float64
 24  In EMC          427 non-null    float64
 25  In Air Density  427 non-null    int64
 26  Wind Samp       427 non-null    int64
 27  Wind Tx         427 non-null    int64
 28  ISS Recept      427 non-null    float64
 29  Arc. Int.       427 non-null    int64
dtypes: datetime64[ns](1), float64(12), int64(5), object(12)
memory usage: 100.2+ KB

In [10]:
# Konversi tipe data Date and Time
aws_bef['Date'] = pd.to_datetime(aws_bef['Date'])
aws_bef['Time'] = pd.to_datetime(aws_bef['Time'], format='%H:%M:%S').dt.time

aws_bef['DateTime'] = aws_bef.apply(lambda row: pd.datetime.combine(row['Date'], row['Time']), axis=1)

<ipython-input-10-3d1d57901208>:5: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  aws_bef['DateTime'] = aws_bef.apply(lambda row: pd.datetime.combine(row['Date'], row['Time']), axis=1)

In [11]:
# Ubah tipe data
columns_bef = ['Temp Out', 'Hi Temp', 'Low Temp', 'Dew Pt.', 'Wind Chill', 'Heat Index', 'THW Index', 'Heat D-D', 'Cool D-D']

for i in columns_bef:
  aws_bef[i] = aws_bef[i].astype(float)

In [12]:
aws_bef.fillna(aws_bef.mean(), inplace=True)

<ipython-input-12-7b5aa9d0d691>:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  aws_bef.fillna(aws_bef.mean(), inplace=True)
<ipython-input-12-7b5aa9d0d691>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  aws_bef.fillna(aws_bef.mean(), inplace=True)

In [13]:
aws_bef.head(10)

,Date,Time,Temp Out,Hi Temp,Low Temp,Out Hum,Dew Pt.,Wind Speed,Wind Dir,Wind Run,Hi Speed,Hi Dir,Wind Chill,Heat Index,THW Index,Bar,Rain,Rain Rate,Heat D-D,Cool D-D,In Temp,In Hum,In Dew,In Heat,In EMC,In Air Density,Wind Samp,Wind Tx,ISS Recept,Arc. Int.,DateTime
0,2023-12-29,10:30:00,32.1,32.4,31.7,69.0,25.7,0.9,N,0.54,2.2,W,32.1,40.4,40.4,1014.0,0.0,0.0,0.0,0.096,31.2,71,25.3,38.4,12.85,11246,227,1,99.6,10,2023-12-29 10:30:00
1,2023-12-29,10:40:00,32.5,32.6,32.4,69.0,26.1,0.9,NNE,0.54,3.6,N,32.5,41.6,41.6,1014.1,0.0,0.0,0.0,0.098,31.2,71,25.3,38.6,12.85,11244,166,1,72.8,10,2023-12-29 10:40:00
2,2023-12-29,10:50:00,32.1,32.4,31.9,72.0,26.4,0.9,NE,0.54,2.2,NE,32.1,41.6,41.6,1014.1,0.0,0.0,0.0,0.096,31.2,71,25.3,38.4,12.85,11246,231,1,100.0,10,2023-12-29 10:50:00
3,2023-12-29,11:00:00,32.0,32.0,31.9,70.0,25.8,0.4,WNW,0.27,1.8,WNW,32.0,40.4,40.4,1013.8,0.0,0.0,0.0,0.095,31.9,70,25.7,40.2,12.55,11207,87,1,38.2,10,2023-12-29 11:00:00
4,2023-12-29,11:10:00,31.8,31.9,31.8,69.0,25.4,0.4,NNW,0.27,2.2,NE,31.8,39.7,39.7,1013.8,0.0,0.0,0.0,0.094,32.0,70,25.8,40.4,12.55,11200,234,1,100.0,10,2023-12-29 11:10:00
5,2023-12-29,11:20:00,31.7,31.8,31.6,70.0,25.5,0.4,NE,0.27,1.8,NE,31.7,39.5,39.5,1013.7,0.0,0.0,0.0,0.093,32.2,68,25.6,40.4,12.05,11197,231,1,100.0,10,2023-12-29 11:20:00
6,2023-12-29,11:30:00,31.7,31.8,31.7,68.0,25.1,1.3,NE,0.80,2.7,NE,31.7,39.0,39.0,1013.7,0.0,0.0,0.0,0.093,32.4,67,25.5,40.7,11.85,11189,232,1,100.0,10,2023-12-29 11:30:00
7,2023-12-29,11:40:00,31.8,32.0,31.7,69.0,25.4,1.3,NE,0.80,3.1,N,31.8,39.7,39.7,1013.7,0.0,0.0,0.0,0.094,32.6,68,25.9,41.3,12.05,11178,234,1,100.0,10,2023-12-29 11:40:00
8,2023-12-29,11:50:00,32.1,32.2,32.0,69.0,25.7,0.4,N,0.27,2.7,NE,32.1,40.4,40.4,1013.5,0.0,0.0,0.0,0.096,32.5,67,25.6,40.8,11.85,11185,230,1,100.0,10,2023-12-29 11:50:00
9,2023-12-29,12:00:00,32.4,32.6,32.2,69.0,26.0,1.3,NNE,0.80,3.6,NNE,32.4,41.2,41.2,1013.6,0.0,0.0,0.0,0.098,32.3,68,25.7,40.7,12.05,11189,235,1,100.0,10,2023-12-29 12:00:00

In [14]:
aws_bef['Wind Dir'].unique()

array(['N', 'NNE', 'NE', 'WNW', 'NNW', 'ENE', 'SSE', 'SE', 'ESE', 'E',
       nan, 'S', 'SSW', 'WSW', 'W', 'SW', 'NW'], dtype=object)

In [15]:
aws_bef['Hi Dir'].unique()

array(['W', 'N', 'NE', 'WNW', 'NNE', 'NW', 'ENE', 'E', 'ESE', 'SE', nan,
       'SSW', 'NNW', 'SW', 'WSW', 'S', 'SSE'], dtype=object)

In [16]:
aws_bef.to_csv('dataAWS_bef.csv')

#### Data Setelah Pengecetan

In [17]:
aws_aft = pd.read_excel('/content/drive/MyDrive/Satu Data/Data KKN/AWS 8 - 11 Januari 2024.xlsx')
aws_aft.head()

,Date,Time,Temp Out,Hi Temp,Low Temp,Out Hum,Dew Pt.,Wind Speed,Wind Dir,Wind Run,Hi Speed,Hi Dir,Wind Chill,Heat Index,THW Index,Bar,Rain,Rain Rate,Heat D-D,Cool D-D,In Temp,In Hum,In Dew,In Heat,In EMC,In Air Density,Wind Samp,Wind Tx,ISS Recept,Arc. Int.
0,08/01/24,10:30,28.8,29.1,28.5,81,25.2,0.4,NNE,0.27,2.2,NNE,28.8,34.6,34.6,1014.9,0.0,0.0,0.000,0.073,28.1,80,24.3,32.7,15.85,1.1391,155,1,68.0,10
1,08/01/24,10:40,29.4,29.7,29.1,77,25.0,0.4,NNE,0.27,1.8,NNE,29.4,35.4,35.4,1014.8,0.0,0.0,0.000,0.077,28.1,80,24.3,32.6,15.85,1.1393,230,1,100.0,10
2,08/01/24,10:50,29.9,30.1,29.7,76,25.2,0.9,NE,0.54,2.7,NE,29.9,36.4,36.4,1014.8,0.0,0.0,0.000,0.080,28.0,80,24.2,32.4,15.85,1.1396,233,1,100.0,10
3,08/01/24,11:00,30.2,30.4,30.1,77,25.7,0.9,NNE,0.54,2.2,NE,30.2,37.6,37.6,1014.7,0.0,0.0,0.000,0.083,28.1,80,24.3,32.6,15.85,1.1392,233,1,100.0,10
4,08/01/24,11:10,---,---,---,76,---,0.0,---,0.00,0.0,---,---,---,---,1014.6,0.0,0.0,---,---,28.3,79,24.3,32.9,15.49,1.1382,0,1,0.0,10

In [18]:
def check_for_dashes(column):
    return '---' in column.values

columns_with_dashes = aws_aft.apply(check_for_dashes)
columns_with_dashes[columns_with_dashes].index.tolist()

<ipython-input-18-63eded135f38>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return '---' in column.values

['Temp Out',
 'Hi Temp',
 'Low Temp',
 'Out Hum',
 'Dew Pt.',
 'Wind Dir',
 'Hi Dir',
 'Wind Chill',
 'Heat Index',
 'THW Index',
 'Heat D-D',
 'Cool D-D']

In [19]:
aws_aft.replace('---', np.nan, inplace=True)

In [20]:
aws_aft.isnull().sum()

Date                0
Time                0
Temp Out            3
Hi Temp             3
Low Temp            3
Out Hum             2
Dew Pt.             3
Wind Speed          0
Wind Dir          120
Wind Run            0
Hi Speed            0
Hi Dir            120
Wind Chill          3
Heat Index          3
THW Index           3
Bar                 0
Rain                0
Rain Rate           0
Heat D-D            3
Cool D-D            3
In Temp             0
In Hum              0
In Dew              0
In Heat             0
In EMC              0
In Air Density      0
Wind Samp           0
Wind Tx             0
ISS Recept          0
Arc. Int.           0
dtype: int64

In [21]:
aws_aft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 30 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            427 non-null    object
 1   Time            427 non-null    object
 2   Temp Out        424 non-null    object
 3   Hi Temp         424 non-null    object
 4   Low Temp        424 non-null    object
 5   Out Hum         425 non-null    object
 6   Dew Pt.         424 non-null    object
 7   Wind Speed      427 non-null    float64
 8   Wind Dir        307 non-null    object
 9   Wind Run        427 non-null    float64
 10  Hi Speed        427 non-null    float64
 11  Hi Dir          307 non-null    object
 12  Wind Chill      424 non-null    object
 13  Heat Index      424 non-null    object
 14  THW Index       424 non-null    object
 15  Bar             427 non-null    float64
 16  Rain            427 non-null    float64
 17  Rain Rate       427 non-null    float64
 18  Heat D-D        424 non-null    object
 19  Cool D-D        424 non-null    object
 20  In Temp         427 non-null    float64
 21  In Hum          427 non-null    int64
 22  In Dew          427 non-null    float64
 23  In Heat         427 non-null    float64
 24  In EMC          427 non-null    float64
 25  In Air Density  427 non-null    float64
 26  Wind Samp       427 non-null    int64
 27  Wind Tx         427 non-null    int64
 28  ISS Recept      427 non-null    float64
 29  Arc. Int.       427 non-null    int64
dtypes: float64(12), int64(4), object(14)
memory usage: 100.2+ KB

In [22]:
# Mengubah format Date and Time
aws_aft['Date'] = pd.to_datetime(aws_aft['Date'], format='%d/%m/%y')
aws_aft['DateTime'] = aws_aft['Date'].astype(str) + ' ' + aws_aft['Time']

aws_aft['DateTime'] = pd.to_datetime(aws_aft['DateTime'], format='%Y-%m-%d %H:%M')

In [23]:
# Ubah tipe data
columns_aft = ['Temp Out', 'Hi Temp','Out Hum','Low Temp', 'Dew Pt.', 'Wind Chill', 'Heat Index', 'THW Index', 'Heat D-D', 'Cool D-D']

for i in columns_aft:
  aws_aft[i] = aws_aft[i].astype(float)

In [24]:
aws_aft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 31 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            427 non-null    datetime64[ns]
 1   Time            427 non-null    object
 2   Temp Out        424 non-null    float64
 3   Hi Temp         424 non-null    float64
 4   Low Temp        424 non-null    float64
 5   Out Hum         425 non-null    float64
 6   Dew Pt.         424 non-null    float64
 7   Wind Speed      427 non-null    float64
 8   Wind Dir        307 non-null    object
 9   Wind Run        427 non-null    float64
 10  Hi Speed        427 non-null    float64
 11  Hi Dir          307 non-null    object
 12  Wind Chill      424 non-null    float64
 13  Heat Index      424 non-null    float64
 14  THW Index       424 non-null    float64
 15  Bar             427 non-null    float64
 16  Rain            427 non-null    float64
 17  Rain Rate       427 non-null    float64
 18  Heat D-D        424 non-null    float64
 19  Cool D-D        424 non-null    float64
 20  In Temp         427 non-null    float64
 21  In Hum          427 non-null    int64
 22  In Dew          427 non-null    float64
 23  In Heat         427 non-null    float64
 24  In EMC          427 non-null    float64
 25  In Air Density  427 non-null    float64
 26  Wind Samp       427 non-null    int64
 27  Wind Tx         427 non-null    int64
 28  ISS Recept      427 non-null    float64
 29  Arc. Int.       427 non-null    int64
 30  DateTime        427 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(22), int64(4), object(3)
memory usage: 103.5+ KB

In [25]:
aws_aft.fillna(aws_aft.mean(), inplace=True)

<ipython-input-25-8146c6ff8546>:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  aws_aft.fillna(aws_aft.mean(), inplace=True)
<ipython-input-25-8146c6ff8546>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  aws_aft.fillna(aws_aft.mean(), inplace=True)

In [26]:
aws_aft.isnull().sum()

Date                0
Time                0
Temp Out            0
Hi Temp             0
Low Temp            0
Out Hum             0
Dew Pt.             0
Wind Speed          0
Wind Dir          120
Wind Run            0
Hi Speed            0
Hi Dir            120
Wind Chill          0
Heat Index          0
THW Index           0
Bar                 0
Rain                0
Rain Rate           0
Heat D-D            0
Cool D-D            0
In Temp             0
In Hum              0
In Dew              0
In Heat             0
In EMC              0
In Air Density      0
Wind Samp           0
Wind Tx             0
ISS Recept          0
Arc. Int.           0
DateTime            0
dtype: int64

In [27]:
aws_aft.head(10)

,Date,Time,Temp Out,Hi Temp,Low Temp,Out Hum,Dew Pt.,Wind Speed,Wind Dir,Wind Run,Hi Speed,Hi Dir,Wind Chill,Heat Index,THW Index,Bar,Rain,Rain Rate,Heat D-D,Cool D-D,In Temp,In Hum,In Dew,In Heat,In EMC,In Air Density,Wind Samp,Wind Tx,ISS Recept,Arc. Int.,DateTime
0,2024-01-08,10:30,28.80000,29.100000,28.500000,81.000000,25.200000,0.4,NNE,0.27,2.2,NNE,28.80000,34.60000,34.60000,1014.9,0.0,0.0,0.0,0.073000,28.1,80,24.3,32.7,15.85,1.1391,155,1,68.0,10,2024-01-08 10:30:00
1,2024-01-08,10:40,29.40000,29.700000,29.100000,77.000000,25.000000,0.4,NNE,0.27,1.8,NNE,29.40000,35.40000,35.40000,1014.8,0.0,0.0,0.0,0.077000,28.1,80,24.3,32.6,15.85,1.1393,230,1,100.0,10,2024-01-08 10:40:00
2,2024-01-08,10:50,29.90000,30.100000,29.700000,76.000000,25.200000,0.9,NE,0.54,2.7,NE,29.90000,36.40000,36.40000,1014.8,0.0,0.0,0.0,0.080000,28.0,80,24.2,32.4,15.85,1.1396,233,1,100.0,10,2024-01-08 10:50:00
3,2024-01-08,11:00,30.20000,30.400000,30.100000,77.000000,25.700000,0.9,NNE,0.54,2.2,NE,30.20000,37.60000,37.60000,1014.7,0.0,0.0,0.0,0.083000,28.1,80,24.3,32.6,15.85,1.1392,233,1,100.0,10,2024-01-08 11:00:00
4,2024-01-08,11:10,26.42783,26.517217,26.342453,76.000000,24.373349,0.0,NaN,0.00,0.0,NaN,26.42783,30.22217,30.22217,1014.6,0.0,0.0,0.0,0.056203,28.3,79,24.3,32.9,15.49,1.1382,0,1,0.0,10,2024-01-08 11:10:00
5,2024-01-08,11:20,26.42783,26.517217,26.342453,89.009412,24.373349,0.0,NaN,0.00,0.0,NaN,26.42783,30.22217,30.22217,1014.4,0.0,0.0,0.0,0.056203,28.6,76,23.9,33.1,14.58,1.1377,0,1,0.0,10,2024-01-08 11:20:00
6,2024-01-08,11:30,26.42783,26.517217,26.342453,89.009412,24.373349,0.0,NaN,0.00,0.0,NaN,26.42783,30.22217,30.22217,1014.3,0.0,0.0,0.0,0.056203,28.7,78,24.4,33.7,15.18,1.1361,0,1,0.0,10,2024-01-08 11:30:00
7,2024-01-08,11:40,31.80000,31.800000,31.700000,73.000000,26.300000,0.4,NNE,0.27,1.3,N,31.80000,40.90000,40.90000,1014.1,0.0,0.0,0.0,0.093000,28.7,76,24.0,33.3,14.58,1.1367,16,1,7.0,10,2024-01-08 11:40:00
8,2024-01-08,11:50,31.80000,31.900000,31.800000,73.000000,26.400000,0.9,WSW,0.54,2.2,ENE,31.80000,41.10000,41.10000,1014.0,0.0,0.0,0.0,0.094000,28.8,75,24.0,33.5,14.27,1.1361,130,1,57.0,10,2024-01-08 11:50:00
9,2024-01-08,12:00,31.80000,31.900000,31.700000,71.000000,25.900000,0.9,NE,0.54,2.7,NNE,31.80000,40.20000,40.20000,1013.9,0.0,0.0,0.0,0.093000,28.8,76,24.2,33.7,14.57,1.1355,208,1,91.2,10,2024-01-08 12:00:00

In [28]:
aws_aft.to_csv('dataAWS_aft.csv')

## Data SERUIT (IoT)

### Data Sebelum Pengecatan

In [31]:
IoT_bef = pd.read_excel('/content/drive/MyDrive/Satu Data/Data KKN/BALDUS SEBELUM PENGECATAN.xlsx')
IoT_bef.head(3)

   Kelembaban  Suhu DHT  Suhu BMP   Tekanan  Ketinggian
0        84.0      32.3     32.18  99871.64      121.71
1        83.0      32.3     32.18  99873.83      121.53
2        84.0      32.3     32.18  99875.69      121.37

In [32]:
IoT_bef.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Kelembaban  6019 non-null   float64
 1   Suhu DHT    6019 non-null   float64
 2   Suhu BMP    6019 non-null   float64
 3   Tekanan     6019 non-null   float64
 4   Ketinggian  6019 non-null   float64
dtypes: float64(5)
memory usage: 235.2 KB

In [33]:
IoT_bef.isnull().sum()

Kelembaban    0
Suhu DHT      0
Suhu BMP      0
Tekanan       0
Ketinggian    0
dtype: int64

In [34]:
IoT_bef = IoT_bef.iloc[:6001]

In [35]:
IoT_bef.to_csv('IoT_bef.csv')

### Data Setelah Pengecatan

In [36]:
IoT_aft = pd.read_excel('/content/drive/MyDrive/Satu Data/Data KKN/BALDUS PASCA PENGECATAN.xlsx')
IoT_aft.head(3)

   Kelembaban  Suhu DHT  Suhu BMP   Tekanan  Ketinggian
0          84      32.3     32.18  998.7164      121.71
1          83      32.3     32.18  998.7383      121.53
2          84      32.3     32.18  998.7569      121.37

In [37]:
IoT_aft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12755 entries, 0 to 12754
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Kelembaban  12755 non-null  int64
 1   Suhu DHT    12755 non-null  float64
 2   Suhu BMP    12755 non-null  float64
 3   Tekanan     12755 non-null  float64
 4   Ketinggian  12755 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 498.4 KB

In [38]:
IoT_aft.isnull().sum()

Kelembaban    0
Suhu DHT      0
Suhu BMP      0
Tekanan       0
Ketinggian    0
dtype: int64

In [39]:
IoT_aft = IoT_aft.iloc[6021:].reset_index(drop=True)

In [40]:
IoT_aft.tail()

      Kelembaban  Suhu DHT  Suhu BMP   Tekanan  Ketinggian
6729          98      28.9     28.81  999.4863      115.23
6730          98      28.9     28.81  999.4846      115.24
6731          98      28.9     28.81  999.4901      115.20
6732          98      28.9     28.81  999.4825      115.26
6733          98      28.9     28.81  999.4846      115.24

In [41]:
IoT_aft.describe()

       Kelembaban     Suhu DHT     Suhu BMP      Tekanan   Ketinggian
count      6734.0  6734.000000  6734.000000  6734.000000  6734.000000
mean         98.0    29.230784    29.225699   999.005031   119.287021
std           0.0     0.756601     0.706537     1.275567    10.733057
min          98.0    26.700000    26.760000   998.014900    92.000000
25%          98.0    28.900000    29.010000   998.162800   116.792500
50%          98.0    29.300000    29.410000   998.449300   123.960000
75%          98.0    29.800000    29.750000   999.300300   126.380000
max          98.0    29.800000    29.910000  1002.248200   127.620000

In [42]:
IoT_aft.to_csv('IoT_aft.csv')